<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="nltc291" ignored="0" name="mtxshop" tests="2" failures="1" timestamp="22 Dec 2021 08:46:04 GMT" time="10.657" errors="0">
  <testcase name="test001_AddCustomer" time="1.799" classname="com.crm.fenceng.testcases.AddCustomerTests"/>
  <testcase name="test001_addContract" time="0.605" classname="com.crm.fenceng.testcases.AddContractTests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [0]
at com.crm.fenceng.testcases.AddContractTests.test001_addContract(AddContractTests.java:20)
at java.util.concurrent.FutureTask.run(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- test001_addContract -->
</testsuite> <!-- mtxshop -->
